# Generated by Django 4.0.6 on 2022-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_movie_remove_watchlist_platform_delete_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
