# Generated by Django 4.0.6 on 2022-07-24 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_watchlist_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaStreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='drama',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drama',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drama', to='watchlist_app.dramastreamplatform'),
            preserve_default=False,
        ),
    ]
