# Generated by Django 4.0.6 on 2022-07-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0011_dramareview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dramareview',
            name='drama',
        ),
        migrations.DeleteModel(
            name='Drama',
        ),
        migrations.DeleteModel(
            name='DramaReview',
        ),
        migrations.DeleteModel(
            name='DramaStreamPlatform',
        ),
    ]
